{
  "swagger": "2.0",
  "info": {
    "title": "Strava API v3",
    "description": "The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to develo[...]",
    "version": "3.0.0"
  },
  "host": "www.strava.com",
  "schemes": [
    "https"
  ],
  "basePath": "/api/v3",
  "securityDefinitions": {
    "strava_oauth": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://www.strava.com/api/v3/oauth/authorize",
      "tokenUrl": "https://www.strava.com/api/v3/oauth/token",
      "scopes": {
        "read": "Read public segments, public routes, public profile data, public posts, public events, club feeds, and leaderboards",
        "read_all": "Read private routes, private segments, and private events for the user",
        "profile:read_all": "Read all profile information even if the user has set their profile visibility to Followers or Only You",
        "profile:write": "Update the user's weight and Functional Threshold Power (FTP), and access to star or unstar segments on their behalf",
        "activity:read": "Read the user's activity data for activities that are visible to Everyone and Followers, excluding privacy zone data",
        "activity:read_all": "The same access as activity:read, plus privacy zone data and access to read the user's activities with visibility set to Only You",
        "activity:write": "Access to create manual activities and uploads, and access to edit any activities that are visible to the app, based on activity read access level"
      }
    }
  },
  "security": [
    {
      "strava_oauth": [
        "public"
      ]
    }
  ],
  "paths": {
    "/athletes/{id}/stats": {
      "get": {
        "operationId": "getStats",
        "summary": "Get Athlete Stats",
        "description": "Returns the activity stats of an athlete. Only includes data from activities set to Everyone visibilty.",
        "tags": [
          "Athletes"
        ]
      }
    },
    "/athlete": {
      "get": {
        "operationId": "getLoggedInAthlete",
        "summary": "Get Authenticated Athlete",
        "description": "Returns the currently authenticated athlete. Tokens with profile:read_all scope will receive a detailed athlete representation; all others will receive a summary representation.",
        "tags": [
          "Athletes"
        ]
      },
      "put": {
        "operationId": "updateLoggedInAthlete",
        "summary": "Update Athlete",
        "description": "Update the currently authenticated athlete. Requires profile:write scope.",
        "tags": [
          "Athletes"
        ]
      }
    },
    "/activities": {
      "post": {
        "operationId": "createActivity",
        "summary": "Create an Activity",
        "description": "Creates a manual activity for an athlete, requires activity:write scope.",
        "tags": [
          "Activities"
        ]
      }
    },
    "/activities/{id}": {
      "get": {
        "operationId": "getActivityById",
        "summary": "Get Activity",
        "description": "Returns the given activity that is owned by the authenticated athlete. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities.",
        "tags": [
          "Activities"
        ]
      },
      "put": {
        "operationId": "updateActivityById",
        "summary": "Update Activity",
        "description": "Updates the given activity that is owned by the authenticated athlete. Requires activity:write. Also requires activity:read_all in order to update Only Me activities",
        "tags": [
          "Activities"
        ]
      }
    },
    "/athlete/activities": {
      "get": {
        "operationId": "getLoggedInAthleteActivities",
        "summary": "List Athlete Activities",
        "description": "Returns the activities of an athlete for a specific identifier. Requires activity:read. Only Me activities will be filtered out unless requested by a token with activity:read_all.",
        "tags": [
          "Activities"
        ]
      }
    },
    "/activities/{id}/comments": {
      "get": {
        "operationId": "getCommentsByActivityId",
        "summary": "List Activity Comments",
        "description": "Returns the comments on the given activity. Requires activity:read for Everyone and Followers activities. Requires activity:read_all for Only Me activities.",
        "tags": [
          "Activities"
        ]
      }
    }
  }
}
